version: '3.7'
services:
  db:
    image: postgres:15
    container_name: my-postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"

  auto-invoice-service:
    build: .
    depends_on:
      - db
    environment:
      PGHOST: db
      PGUSER: myuser
      PGPASSWORD: mypass
      PGDATABASE: mydb
    ports:
      - "3000:3000"